# Generated by Django 4.1.3 on 2022-11-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Residencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cidade", models.CharField(max_length=40, verbose_name="Cidade")),
                ("bairro", models.CharField(max_length=40, verbose_name="Bairro")),
                ("estado", models.CharField(max_length=40, verbose_name="Estado")),
                ("cep", models.CharField(max_length=8, verbose_name="CEP")),
                (
                    "numero",
                    models.IntegerField(verbose_name="Número da residência"),
                ),
            ],
            options={
                "verbose_name": "Cadastro de residência",
                "unique_together": {("cep", "numero")},
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                ("nome", models.CharField(max_length=30, verbose_name="Nome")),
                (
                    "cpf",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="CPF",
                    ),
                ),
                ("idade", models.IntegerField(verbose_name="Idade")),
                (
                    "escolaridade",
                    models.IntegerField(
                        choices=[
                            (1, "Analfabeto"),
                            (2, "Ensino básico"),
                            (3, "Fundamental incompleto"),
                            (4, "Fundamental completo"),
                            (5, "Ensino médio incompleto"),
                            (6, "Ensino médio completo"),
                            (7, "Ensino superior incompleto"),
                            (8, "Ensino superior completo"),
                            (9, "Mestrado/Doutorado"),
                        ],
                        verbose_name="Escolaridade",
                    ),
                ),
                (
                    "residencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="censo_api.residencia",
                        verbose_name="Residência",
                    ),
                ),
            ],
        ),
    ]
